version: '3.9'
services:

  agenda:
    container_name: modaresa-agenda
    build:
      context: ./agenda
    volumes:
      - .:/modaresa/src/app
      - /modaresa/src/app/node_modules/
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
